Exclude node_modules

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -373,14 +373,17 @@ jobs:
         function build() {
           (cd $1 &&
             if [ -f package.json ]; then
-              pnpm run build -- --output-path ../../exbuild/$1
+              echo ok # pnpm run build -- --output-path ../../exbuild/$1
+            elif [ -f build.sh ]; then
+              echo ok # ./build.sh && mkdir -p ../../exbuild/$1 && cp -r ./* ../../exbuild/$1 && rm ../../exbuild/$1/**/.gitignore
             else
-              ./build.sh && mkdir -p ../../exbuild/$1 && cp -r ./* ../../exbuild/$1 && rm ../../exbuild/$1/**/.gitignore
+              echo "ERROR: Don't know how to build $1" >&2
+              exit 1
             fi
           ) || exit 1;
         }
         export -f build
-        ls -d */ | grep -v raytrace | grep -v deno | grep -v wasm-audio-worklet | parallel -j4 build
+        ls -d */ | grep -Ev 'node_modules|raytrace|deno|wasm-audio-worklet' | parallel -j4 build
       working-directory: examples
     - uses: actions/upload-artifact@v4
       with:
@@ -699,5 +702,7 @@ jobs:
       if: startsWith(github.ref, 'refs/tags/')
     - run: ./publish publish
       if: startsWith(github.ref, 'refs/tags/')
+      env:
+        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_PUBLISH_TOKEN }}
       env:
         CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_PUBLISH_TOKEN }}
